name: Job Alerts (Hourly Email)

on:
  schedule:
    - cron: "0 * * * *"   # every hour on the hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run monitor
        run: python monitor.py
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}
      - name: Persist seen.json if changed
        run: |
          if [[ -n "$(git status --porcelain seen.json)" ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add seen.json
            git commit -m "Update seen.json [skip ci]"
            git push
          fi
